import plasma_core.constants
from plasma_core.transaction import Transaction

EXIT_PERIOD = plasma_core.constants.MIN_EXIT_PERIOD

SAFE_GAS_STIPEND = 2300

INITIAL_IMMUNE_VAULTS = 2
INITIAL_IMMUNE_EXIT_GAMES = 1

GAS_LIMIT = 10000000
START_GAS = GAS_LIMIT - 1000000

INITIAL_ETH = 10000 * 10 ** 18

PAYMENT_TX_MAX_INPUT_SIZE = Transaction.NUM_INPUTS
PAYMENT_TX_MAX_OUTPUT_SIZE = Transaction.NUM_OUTPUTS
