NULL_BYTE = b'\x00'
NULL_HASH = NULL_BYTE * 32
NULL_SIGNATURE = NULL_BYTE * 65
NULL_ADDRESS = NULL_BYTE * 20
NULL_ADDRESS_HEX = '0x' + NULL_ADDRESS.hex()
EMPTY_METADATA = b''

MINUTE = 60
DAY = 60 * 60 * 24

# used for suitable test contract instantiation
MIN_EXIT_PERIOD = 4 * MINUTE

CHILD_BLOCK_INTERVAL = 1000
