init_multisig:
	cp ../MultiSigWalletOverride/migrations/* ../MultiSigWallet/migrations
	cp ../MultiSigWalletOverride/truffle.js ../MultiSigWallet/
	cp ../MultiSigWalletOverride/package.js ../MultiSigWallet/
	cp ../MultiSigWalletOverride/package-lock.json ../MultiSigWallet/
